"""modify image table

Revision ID: 58424cbfccdd
Revises: 9633a0cd53ca
Create Date: 2024-01-22 18:18:53.358426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58424cbfccdd'
down_revision: Union[str, None] = '9633a0cd53ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_image_key', 'images', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('images_image_key', 'images', ['image'])
    # ### end Alembic commands ###
