"""modify user model and add job and gender columns

Revision ID: a4c525c13c4e
Revises: 314b0f27ab24
Create Date: 2024-01-22 15:40:47.988130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c525c13c4e'
down_revision: Union[str, None] = '314b0f27ab24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    op.add_column('users', sa.Column('job', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
