"""modify Image table

Revision ID: d039c2ddbdf1
Revises: 2bdb02c88e80
Create Date: 2024-01-22 17:14:41.165336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd039c2ddbdf1'
down_revision: Union[str, None] = '2bdb02c88e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
